### PR TITLE
fastboot-compat

### PR DESCRIPTION
**Pull request by davidpett**
made fastboot ready

### CODE REVIEW

**Comment by aaronbhansen** [comment]
@davidpett awesome thanks for doing this. I'm going to look at it soon and work on getting this merged in

**Comment by matbox** [comment]
@aaronbhansen Looks like this should be ready to get merged?

**Comment by deanmraz** [comment]
@aaronbhansen how does this look?

**Comment by w96k** [comment]
ReferenceError: jQuery is not defined

**Comment by deanmraz** [comment]
@davidpett upgraded you're work to use the v1 fastboot api https://github.com/Semantic-Org/Semantic-UI-Ember/pull/204

**Comment by aureliosaraiva** [comment]
Closed in favor: https://github.com/Semantic-Org/Semantic-UI-Ember/pull/204

**Pull request closed without merging**
