### PR TITLE
[WIP] Add support for Ember 2.x

### PR DESCRIPTION
**Pull request by andrewbranch**
Ember 2.0.0-beta.1 was released yesterday, and with it all deprecations added in the 1.x series were removed from the codebase. Semantic-UI-Ember is built on Ember 1.8.1, which means that people using Ember >1.8.1 and <2.0.0 are receiving a bunch of deprecation warnings, and those using Ember 2.x going forward aren't able to use this addon at all. I'm intending to update this addon to replace deprecated code and be compatible with Ember 2.x, while maintaining compatibility with Ember >=1.8.1.

 - [x] Update dependencies so we see all the deprecations
 - [ ] Replace deprecated code
 - [ ] Test against multiple versions of Ember

### CODE REVIEW

**Comment by andrewbranch** [comment]
Wait. Are there really no tests?

**Comment by nathanpalmer** [comment]
@andrewbranch Yes! No tests. All the components are working as they are used daily in multiple production apps. The plan was to get tests added in before this moved out of the beta/alpha stage.

**Comment by andrewbranch** [comment]
@nathanpalmer Gotcha. On the one hand, adding comprehensive tests is beyond the scope of this PR. On the other hand, it would be helpful to know that my changes didn't break everything. I guess I'll just see what I have time for. 😛

**Comment by aaronbhansen** [comment]
@andrewbranch, I merged some changes into master which might conflict with some of your changes.

**Comment by andrewbranch** [comment]
That's ok, sorry I haven't had time to tackle more of this. I was hoping to get this done without making breaking changes, but the modals rely heavily on view-related API, which is deprecated for public use in 2.x.

I like [this approach](https://dockyard.com/blog/2015/06/08/a-clean-pattern-for-modal-dialogs), which makes use of the `{{component}}` helper, added in Ember 1.10. Are you ok dropping 1.8 and 1.9? I don't really know the guidelines for publishing addons, or your specific priorities for this one.

**Comment by aaronbhansen** [comment]
@andrewbranch i think the ```{{component}}`` feature is only relevant to the users code base. Meaning they could use named components or that helper and still get the same functionality. The internals for launching a modal would still be the same for this library.

Also, I was thinking we are going to convert the remaining individual pieces to remove deprecations one at a time. i.e. dropdown, then modal, then what ever is left. I want to look at the Ember select and pull over code that is still relevant, and remove parts that aren't. Also for the modal, we do want to go all in on components, but we want to research how a few of the other ember modal addons have tackled this to see if there is a best way to do modals that works with Semantic and it's transitions. 

Looking at the code between this and master, I think I merged in changes for most of what you had. Maybe we put the rest of the changes on hold while we research a little more into the best way to handle the remaining pieces.

**Comment by andrewbranch** [comment]
The `{{component}}` helper would be in this library, leaving user code to look more like

```
<button {{action "showModal" "my-component-name" contextForModal}}>Show the modal!</button>
```

(`{{component}}` is what allows the addon code, under the hood, to use the `"my-component-name"` string and render that component.)

But it sounds like that’s a moot point. That’s fine; I started this because it appeared that no one else was really going to do it:
> the same version should continue to work

I may need to continue to develop my fork, depending on how quickly you get up to speed with 2.0, so if that happens and you become interested in merging, I’ll be happy to help reconcile any divergences between our codebases.

**Pull request closed without merging**
