### PR TITLE
bumped @ember/optional-features to 1.3.0

### PR DESCRIPTION
**Pull request by Unkrass**
fixes https://github.com/Semantic-Org/Semantic-UI-Ember/issues/261

### CODE REVIEW

**Comment by topbloc-beiswenger** [comment]
@aaronbhansen Can we get a release with this update?

**Comment by aaronbhansen** [comment]
I'm not longer maintaining this, would you like to be added to the repo and npm?

**Comment by topbloc-beiswenger** [comment]
No that's not necessary. Do you know if there are any active maintainers that would be able to publish a new release?

**Comment by kushthedude** [comment]
I can publish a gh release.

**Comment by kushthedude** [comment]
Done @topbloc-beiswenger !

**Comment by topbloc-beiswenger** [comment]
Thank you!

**Comment by topbloc-beiswenger** [comment]
@kushthedude Can we also get this published on npm?

**Comment by kushthedude** [comment]
> @kushthedude Can we also get this published on npm?

I don't have access to npm registry 😅

**Comment by topbloc-beiswenger** [comment]
@aaronbhansen Would you mind adding me or @kushthedude to npm so we can get this published? This is currently our only blocker for upgrading Ember versions.

**Comment by topbloc-beiswenger** [comment]
@aaronbhansen Any updates? 
@nathanpalmer Would you be able to publish a new npm release?

**Comment by nathanpalmer** [comment]
@topbloc-beiswenger @kushthedude Send me your npm usernames and I might be able to add you.

**Comment by kushthedude** [comment]
kushthedude

**Comment by topbloc-beiswenger** [comment]
mattbeiswenger

**Comment by nathanpalmer** [comment]
I added both of you to the npm package. @kushthedude @topbloc-beiswenger

**Comment by kushthedude** [comment]
> @aaronbhansen Any updates?
> @nathanpalmer Would you be able to publish a new npm release?

Published 3.0.5 to npm

**Pull request merged**
