### PR TITLE
[WIP] Refactoring and new feature

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by aaronbhansen** [comment]
@listepo I'm not sure what you're trying to do with this pull request. You remove the ability to dynamically extend semantic components from parameters with the base mixin. You add an empty semantic mixin, and no real unit tests to support your changes. Feels like a huge step backwards.

**Comment by listepo** [comment]
@aaronbhansen ```addon/mixins/module-settings.js``` can specify settings for any semantic component. I have not suffered a lot with the fact that I use in my project. When do and add examples you will understand what I am aiming.

**Comment by aaronbhansen** [comment]
With how things are today, you can do something like this
```{{ui-popup position="top center"}}``` and its automatically applied to semantic. With what you want to do, you would have do with do 
```
UiPopup.extend({
   settings: { position: "top center" }
})
```
or 
```
ParentController.extend({
  popupSettings: { position: 'top center' }
})
```
and then
```
{{ui-popup settings=popupSettings}}
```

That seems like a whole lot more work for the same effect as today.

**Comment by listepo** [comment]
I believe that it is not safe, as the names of the properties of the system Semantic and Ember may intersect, then what to do?

**Comment by aaronbhansen** [comment]
In the rare case there is a conflict, we alias the key ui_{property_name}. It's all in the base mixin https://github.com/Semantic-Org/Semantic-UI-Ember/blob/master/addon/mixins/base.js

**Comment by listepo** [comment]
OK, I understand your approach, thank you.

**Pull request closed without merging**
