### PR TITLE
Ember and Semantic Upgrades

### PR DESCRIPTION
**Pull request by nathanpalmer**
Everything on this list is complete. I'll just want to run through some additional tests before we merge it in. This does include several breaking changes though so any feedback is helpful.

# Ember Upgrade
The latest version of Ember brings deprecations and incompatibilities with this library. It's mostly because we were piggy-backing on their internal helpers.

 - [x] Upgrade to Ember 1.13
 - [x] Verify it works with [Ember 2.0](http://emberjs.com/blog/2015/08/13/ember-2-0-released.html)
 - [x] Make sure we're DDAU (Data Down Action Up)
 - [x] Update Dropdown to be compatible without Ember.Select
 - [x] Update Modal to remove usage of Ember.View

# Semantic Upgrade
We need to ensure that this is compatible with Semantic 2.0

 - [x] Upgrade to Semantic 2.0
 - [x] Optional css/js/font includes
 - [x] Semantic Theme Support

# Components
Here to finish out support for any components we're missing. Most are marked with a question-mark so we can decide whether it adds value to implement.
  - [x] Accordion
  - [x] Checkbox
  - [x] Dimmer (no component, can be called directly)
  - [x] Dropdown
  - [x] Embed
  - [x] Modal
  - [x] Nag
  - [x] Popup
  - [x] Progress
  - [x] Radio
  - [x] Rating
  - [x] Search
  - [x] Shape
  - [x] Sidebar
  - [x] Sticky
  - [x] Tab (no component, use ember routes instead)
  - [x] Transition (no component, can be called directly)

# Tests
When this was first released it was used in 2+ production apps so we knew everything was working as expected. Now we need to add tests to ensure we aren't introducing regressions.

 - [x] Add Tests for Accordion
 - [x] Add Tests for Checkbox
 - [x] Add Tests for Dropdown
 - [x] Add Tests for Embed
 - [x] Add Tests for Modal
 - [x] Add Tests for Nag
 - [x] Add Tests for Popup
 - [x] Add Tests for Progress
 - [x] Add Tests for Radio
 - [x] Add Tests for Rating
 - [x] Add Tests for Search
 - [x] Add Tests for Shape
 - [x] Add Tests for Sidebar
 - [x] Add Tests for Sticky

# Breaking Changes

## Dropdown
The dropdown has probably the most significant changes to it since it was previously using the Ember.Select view that doesn't exist today. Instead we've gone light-weight and out of the way. What the means is the ui-dropdown must specify the content which gives you the greatest flexibility and allows you to follow semantic-ui docs.

```handlebars
{{#ui-dropdown class="selection" value=gender}}
  <div class="default text">Gender</div>
  <i class="dropdown icon"></i>
  <div class="menu">
  {{#each genders as |gender|}}
    <div class="item" data-value={{gender.id}}>
      {{gender.text}}
    </div>
  {{/each}}
  </div>
{{/ui-dropdown}}
```

Binding value to gender ensures that whatever semantic is spitting out for values (based on the data-value binding above) is what gets set.

You can also follow DDAU (Data Down Action Up) by specifying an action here instead.

```handlebars
{{#ui-dropdown class="selection" onChange=(action 'update_gender')}}
```

If you want to bind to an object instead of a value you'll need to use the ``{{ui-dropdown-item}}` component like this.

```handlebars
{{#ui-dropdown class="selection" value=gender2}}
  <div class="default text">Gender</div>
  <i class="dropdown icon"></i>
  <div class="menu">
  {{#each genders as |gender|}}
    {{#ui-dropdown-item content=gender}}
      {{gender.text}}
    {{/ui-dropdown-item}}
  {{/each}}
  </div>
{{/ui-dropdown}}
```

## Modal 
Modals are now components and much like semantic-ui's master documentation they need to be placed on the page they will be invoked on.

```handlebars
{{#ui-modal name="profile" class="profile" approve=(action 'approveModal') deny=(action 'denyModal')}}
  <i class="close icon"></i>
  <div class="header">
    Profile Picture
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="http://semantic-ui.com/images/avatar/large/chris.jpg">
    </div>
    <div class="description">
      <div class="ui header">We've auto-chosen a profile image for you.</div>
      <p>We've grabbed the following image from the <a href="https://www.gravatar.com" target="_blank">gravatar</a> image associated with your registered e-mail address.</p>
      <p>Is it okay to use this photo?</p>
    </div>
  </div>
  <div class="actions">
    <div class="ui black deny button">
      Nope
    </div>
    <div class="ui positive right labeled icon button">
      Yep, that's me
      <i class="checkmark icon"></i>
    </div>
  </div>
{{/ui-modal}}
```

You can invoke this using the standard `$('.ui.modal').modal('show')`

### CODE REVIEW

**Comment by jlukic** [comment]
:+1:

**Comment by listepo** [comment]
+1

**Comment by joebartels** [comment]
+1

**Comment by listepo** [comment]
When the beta release?

**Comment by jlukic** [comment]
@nathanpalmer Check out https://github.com/Semantic-Org/Semantic-UI/issues/2858

**Comment by nathanpalmer** [comment]
@jlukic Just saw the other semantic issue this morning. The upgrade to Ember 1.13 support in this branch should also be compatible with Ember 2.0 but we'll run some tests there to make sure. More progress to come this week.

**Comment by jlukic** [comment]
Thanks for the feedback, let me know how it goes.

**Comment by aaronbhansen** [comment]
@jlukic just an update on this, we have all the items done we wanted to do for the 2.0 initial ember / semantic release. We are going to start testing and finalizing the branch to merge in

**Comment by jlukic** [comment]
Kudos, great work!

**Comment by xgenvn** [comment]
+1
I've been watching this recently, ember and ember-cli are changing quite fast. Most of tutorials I found not help or not work out the right way. Well, I hope this will be pulled in soon so that I can try it out again.

**Comment by balupton** [comment]
@xgenvn I've found the exact same thing https://github.com/balupton/can-you-move-to-ember-yet

**Comment by john-griffin** [comment]
Have been using this branch on a project and so far it's working great, thanks!

**Comment by listepo** [comment]
https://gist.github.com/listepo/b48ba4bca5a3361ea94e

**Comment by nathanpalmer** [comment]
@john-griffin Glad to hear it!

We're getting close to merging it in and releasing. Will probably merge and release a 0.9x version in the next day or so unless someone has found a pressing issue on this branch. Seems many are already using it directly.

**Pull request merged**
