### PR TITLE
Upgrade Ember-CLI, Ember and start to add tests

### PR DESCRIPTION
**Pull request by mfeckie**
- [x] Upgrade Ember-CLI
- [x] Convert to new `ember-cli-build.js` and remove `Brocfile.js`
- [x] Add CSP to make the console less noisy during tests
- [x] Convert to new style component layout imports
- [x] Add test for ui-accordion
- [x] Add test for ui-checkbox
- [ ] Migrate dropdown to not use Ember.Select
- [ ] Tests for dropdown

### CODE REVIEW

**Comment by aaronbhansen** [comment]
Thanks, I'll take a look at this and test it in the next day or two. One issue others had was with the dropdown on 1.13. Were you able to test that at all?

**Comment by mfeckie** [comment]
@aaronbhansen, the dropdown is a biggie because Ember.Select being deprecated which is a good thing :tm: , but needs a fair bit more effort.  I'm working on testing and replacing it.  How about I keep pushing to this PR and at some point in the future we talk some more?

**Comment by aaronbhansen** [comment]
I'd like to keep it separate for now, as I don't know the best approach. Let's create a separate issue to discuss it and get feedback from multiple users just related to the dropdown. Separate issue, but related, we also need one for modal and moving it to components. Be good to get discussions going on both.

**Comment by mfeckie** [comment]
OK @aaronbhansen, sorry, this PR actually would be a breaking one then, without the dropdown work I don't think this would be viable.

Perhaps I create a separate PR that just adds tests and CSP stuff for now?

**Comment by aaronbhansen** [comment]
Yeah as you have it at the moment is good, without dropdown changes. Then we can create a proposal for the dropdown to see what might work best

**Comment by listepo** [comment]
+1

**Comment by optikfluffel** [comment]
:+1:

**Pull request closed without merging**
