### PR TITLE
Update README.md -> SemanticRouteMixin path was wrong

### PR DESCRIPTION
**Pull request by EhsanYousefi**
In README.md you guys mentioned to wrong path for SemanticRouteMixin.

### CODE REVIEW

**Comment by fizz** [comment]
@EhsanYousefi I'm afraid you're mistaken :-) It was weird for me to wrap my head around it too, but the semanticroutemixin is indeed the application route from the addon (it provides openModal and closeModal and manages the modals outlet)...the modal mixin is for extending Semantic's modal from your own views (hopefully sometime soon, your own components). I have a few modal views, it's pretty elegant now that I take it for granted. At bare minimum, you can extend the modal mixin to override the default animation with one of the other options semantic offers. 

I'm partial to `fly down` cuz it's dramatic :-)

**Comment by EhsanYousefi** [comment]
SemanticUi-Ember master branch is different with ember-cli server, ember-cli version should be synced with master.
I just installed manually from master branch, every thing works fine.

**Comment by nathanpalmer** [comment]
Because ember has removed `Ember.View` and Controllers are going away we're moving to components which will likely deprecate the SemanticRouteMixin. See #46 for more info.

**Comment by nathanpalmer** [comment]
We've just merged and released version 0.90 which removes the `Ember.View`

**Pull request closed without merging**
