### PR TITLE
Update dependencies, fix jshint errors and tests

### PR DESCRIPTION
**Pull request by listepo**

### CODE REVIEW

**Comment by aaronbhansen** [comment]
Thanks, I'll pull this down and check it out later this week, then get it merged in.

**Comment by listepo** [comment]
Maybe replace __indexOf on http://emberjs.com/api/classes/Ember.Array.html#method_contains

**Comment by aaronbhansen** [comment]
I like that idea. I started updating to ember cli 0.2.5 and removed prototype extensions. I used this branch to compare against to see if we had the same changes. It's pretty similar, I'll change the array contains to ember https://github.com/Semantic-Org/Semantic-UI-Ember/tree/ember-cli-0.2.5

**Comment by aaronbhansen** [comment]
I merged in another branch which had the ember cli 0.2.5 changes.  I think this included all your changes. Closing for now

**Pull request closed without merging**
